FileVersion = 1

[Project]
Name = "libyaml-beef"
DefaultNamespace = "libyaml"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libyaml_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\libyaml.lib"]
